[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["김은미 <eunmi.kim@toss.im>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
Mako = { git = "https://github.com/sqlalchemy/mako.git", tag = "rel_1_2_2" }
mlflow = "2.1.1"
transformers = "^4.26.1"
torch = "^1.13.1"
sentencepiece = "^0.1.97"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
