[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["김은미 <eunmi.kim@toss.im>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
transformers = "^4.27.4"
jupyter = "^1.0.0"
torch = "^2.0.0"
torchvision = "^0.15.1"
torchaudio = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
